import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "./theme";
import { ThemeProviderContext } from "./context/ThemeContext";
import NavBar from "./components/NavBar";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <AppRouterCacheProvider>

          <ThemeProviderContext>
            <ThemeProvider theme={theme}>
              <NavBar />


              {children}
            </ThemeProvider>
          </ThemeProviderContext>




        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
