import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

import { ThemeProviderContext } from "./context/ThemeContext";
import NavBar from "./components/NavBar";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <AppRouterCacheProvider>

          <ThemeProviderContext>
           
              <NavBar />


              {children}
          
          </ThemeProviderContext>




        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
